name: Documentation

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        shell: julia --color=yes --project=docs/ {0}
        run: |
          using Pkg
          Pkg.develop(PackageSpec(path="lib/MPIPreferences"))
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
          Pkg.build(;verbose=true)
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=docs/ docs/make.jl
