name: Unit Tests

on:
  pull_request:
    paths: &paths
      - '.github/workflows/UnitTests.yml'
      - 'Project.toml'
      - 'bin/**'
      - 'deps/**'
      - 'src/**'
      - 'test/**'
      - 'lib/**'
  push:
    branches:
      - master
      - release-*
    paths: *paths

concurrency:
  # Skip intermediate builds: all builds except for builds on the `master` branch
  # Cancel intermediate builds: only pull request builds
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  #TODO test-default:
  #TODO   timeout-minutes: 20
  #TODO   strategy:
  #TODO     matrix:
  #TODO       os:
  #TODO         - macos-15-intel
  #TODO         - ubuntu-latest
  #TODO         - windows-latest
  #TODO       julia_version:
  #TODO         - "min"
  #TODO         - "1"
  #TODO         - "nightly"
  #TODO       julia_arch: [x64, x86]
  #TODO       exclude:
  #TODO         - os: macos-15-intel
  #TODO           julia_arch: x86
  #TODO       include:
  #TODO         - os: macos-15
  #TODO           julia_arch: "aarch64"
  #TODO           julia_version: "1"
  #TODO 
  #TODO     fail-fast: false
  #TODO 
  #TODO   runs-on: ${{ matrix.os }}
  #TODO 
  #TODO   steps:
  #TODO   - name: Checkout
  #TODO     uses: actions/checkout@v6
  #TODO 
  #TODO   - uses: julia-actions/setup-julia@v2
  #TODO     with:
  #TODO       arch: ${{ matrix.julia_arch }}
  #TODO       version: ${{ matrix.julia_version }}
  #TODO   - uses: julia-actions/cache@v3
  #TODO 
  #TODO   - name: add MPIPreferences
  #TODO     shell: julia --color=yes --project=. {0}
  #TODO     run: |
  #TODO       using Pkg
  #TODO       Pkg.develop(path="lib/MPIPreferences")
  #TODO 
  #TODO   - uses: julia-actions/julia-runtest@v1
  #TODO   - uses: julia-actions/julia-processcoverage@v1
  #TODO     # Allow CI to pass even if the `processcoverage` step fails:
  #TODO     continue-on-error: true
  #TODO   - uses: codecov/codecov-action@v6
  #TODO     with:
  #TODO       token: ${{ secrets.CODECOV_TOKEN }}
  #TODO       fail_ci_if_error: false
  #TODO       files: lcov.info
  #TODO   - uses: julia-actions/julia-uploadcoveralls@v1
  #TODO     continue-on-error: true
  #TODO     env:
  #TODO       COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}

  test-mpiabi-jll:
    timeout-minutes: 20
    strategy:
      matrix:
        include:
          #TODO - julia_arch: "arm64"
          #TODO   os: "macOS-26"
          #TODO   julia_version: "1"
          #TODO - julia_arch: "arm64"
          #TODO   os: "ubuntu-24.04-arm"
          #TODO   julia_version: "1"
          #TODO - julia_arch: "x64"
          #TODO   os: "macOS-15-intel"
          #TODO   julia_version: "1"
          - julia_arch: "x64"
            os: "ubuntu-24.04"
            julia_version: "1"
          - julia_arch: "x86"
            os: "ubuntu-24.04"
            julia_version: "1"
          #TODO - julia_arch: "x64"
          #TODO   os: "ubuntu-24.04"
          #TODO   julia_version: "min"
          #TODO - julia_arch: "x64"
          #TODO   os: "ubuntu-24.04"
          #TODO   julia_version: "nightly"

      fail-fast: false
    env:
      JULIA_MPI_TEST_BINARY: MPIABI_jll
      JULIA_MPI_TEST_ABI: MPIABI

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - uses: julia-actions/setup-julia@v2
      with:
        arch: ${{ matrix.julia_arch }}
        version: ${{ matrix.julia_version }}
    - uses: julia-actions/cache@v3

    - name: add MPIPreferences
      shell: julia --color=yes --project=. {0}
      run: |
        using Pkg
        Pkg.develop(path="lib/MPIPreferences")

    - name: use MPIABI_jll
      shell: julia --color=yes --project=test {0}
      run: |
        using Pkg
        Pkg.develop(path="lib/MPIPreferences")
        using MPIPreferences
        MPIPreferences.use_jll_binary("MPIABI_jll", export_prefs=true)
        rm("test/Manifest.toml")

    - uses: julia-actions/julia-runtest@v1

  #TODO test-openmpi-jll:
  #TODO   timeout-minutes: 20
  #TODO   strategy:
  #TODO     matrix:
  #TODO       os:
  #TODO         - macos-15-intel
  #TODO         - ubuntu-latest
  #TODO       julia_version:
  #TODO         - "min"
  #TODO         - "1"
  #TODO         - "nightly"
  #TODO       julia_arch: [x64]
  #TODO 
  #TODO     fail-fast: false
  #TODO   env:
  #TODO     JULIA_MPI_TEST_BINARY: OpenMPI_jll
  #TODO     JULIA_MPI_TEST_ABI: OpenMPI
  #TODO     OMPI_MCA_btl_base_warn_component_unused: 0
  #TODO     OMPI_MCA_rmaps_base_oversubscribe: true
  #TODO     # Allow oversubscription
  #TODO     PRTE_MCA_rmaps_default_mapping_policy: :oversubscribe
  #TODO 
  #TODO   runs-on: ${{ matrix.os }}
  #TODO 
  #TODO   steps:
  #TODO   - name: Checkout
  #TODO     uses: actions/checkout@v6
  #TODO 
  #TODO   - uses: julia-actions/setup-julia@v2
  #TODO     with:
  #TODO       arch: ${{ matrix.julia_arch }}
  #TODO       version: ${{ matrix.julia_version }}
  #TODO   - uses: julia-actions/cache@v3
  #TODO 
  #TODO   - name: add MPIPreferences
  #TODO     shell: julia --color=yes --project=. {0}
  #TODO     run: |
  #TODO       using Pkg
  #TODO       Pkg.develop(path="lib/MPIPreferences")
  #TODO 
  #TODO   - name: use OpenMPI_jll
  #TODO     shell: julia --color=yes --project=test {0}
  #TODO     run: |
  #TODO       using Pkg
  #TODO       Pkg.develop(path="lib/MPIPreferences")
  #TODO       using MPIPreferences
  #TODO       MPIPreferences.use_jll_binary("OpenMPI_jll", export_prefs=true)
  #TODO       rm("test/Manifest.toml")
  #TODO 
  #TODO   - uses: julia-actions/julia-runtest@v1
  #TODO 
  #TODO test-system-brew:
  #TODO   timeout-minutes: 20
  #TODO   strategy:
  #TODO     matrix:
  #TODO       os:
  #TODO         - macos-15
  #TODO         - macos-15-intel
  #TODO       mpi:
  #TODO         - mpich
  #TODO         - openmpi
  #TODO       julia_version:
  #TODO         - "1"
  #TODO       julia_arch:
  #TODO         - "x64"
  #TODO         - "aarch64"
  #TODO       exclude:
  #TODO         - os: macos-15-intel
  #TODO           julia_arch: "aarch64"
  #TODO         - os: macos-15
  #TODO           julia_arch: "x64"
  #TODO 
  #TODO     fail-fast: false
  #TODO 
  #TODO   runs-on: ${{ matrix.os }}
  #TODO   env:
  #TODO     JULIA_MPI_TEST_BINARY: system
  #TODO     ZES_ENABLE_SYSMAN: 1  # https://github.com/open-mpi/ompi/issues/10142
  #TODO 
  #TODO   steps:
  #TODO   - name: Checkout
  #TODO     uses: actions/checkout@v6
  #TODO 
  #TODO   - name: Install MPI via homebrew
  #TODO     run: |
  #TODO       brew install "${{ matrix.mpi }}"
  #TODO 
  #TODO   - uses: julia-actions/setup-julia@v2
  #TODO     with:
  #TODO       version: ${{ matrix.julia_version }}
  #TODO       arch: ${{ matrix.julia_arch }}
  #TODO 
  #TODO   - uses: julia-actions/cache@v3
  #TODO   - name: add MPIPreferences
  #TODO     shell: julia --color=yes --project=. {0}
  #TODO     run: |
  #TODO       using Pkg
  #TODO       Pkg.develop(path="lib/MPIPreferences")
  #TODO 
  #TODO   - name: use system MPI
  #TODO     shell: julia --color=yes --project=. {0}
  #TODO     run: |
  #TODO       using MPIPreferences
  #TODO       mpi_prefix = readchomp(`brew --prefix ${{ matrix.mpi }}`)
  #TODO       libdir = joinpath(mpi_prefix, "lib")
  #TODO       MPIPreferences.use_system_binary(; extra_paths=[libdir])
  #TODO 
  #TODO   - uses: julia-actions/julia-runtest@v1
  #TODO     env:
  #TODO       # TODO: Only disable this test for MPICH. OpenMPI works fine.
  #TODO       JULIA_MPI_TEST_DISABLE_REDUCE_ON_APPLE: 1
  #TODO 
  #TODO 
  #TODO test-system-apt:
  #TODO   timeout-minutes: 20
  #TODO   strategy:
  #TODO     matrix:
  #TODO       mpi:
  #TODO         # MPICH in Ubuntu is currently broken: https://github.com/pmodels/mpich/issues/7064
  #TODO         # - libmpich-dev
  #TODO         - libopenmpi-dev
  #TODO       julia_version:
  #TODO         - "1"
  #TODO 
  #TODO     fail-fast: false
  #TODO 
  #TODO   runs-on: ubuntu-24.04
  #TODO 
  #TODO   env:
  #TODO     JULIA_MPI_TEST_BINARY: system
  #TODO     OMPI_MCA_btl_base_warn_component_unused: 0
  #TODO     OMPI_MCA_rmaps_base_oversubscribe: true
  #TODO 
  #TODO   steps:
  #TODO   - name: Checkout
  #TODO     uses: actions/checkout@v6
  #TODO 
  #TODO   - name: Install MPI via apt
  #TODO     run: |
  #TODO       sudo apt-get update
  #TODO       sudo apt-get install $MPI
  #TODO     env:
  #TODO       MPI: ${{ matrix.mpi }}
  #TODO 
  #TODO   - uses: julia-actions/setup-julia@v2
  #TODO     with:
  #TODO       version: ${{ matrix.julia_version }}
  #TODO 
  #TODO   - uses: julia-actions/cache@v3
  #TODO   - name: add MPIPreferences
  #TODO     shell: julia --color=yes --project=. {0}
  #TODO     run: |
  #TODO       using Pkg
  #TODO       Pkg.develop(path="lib/MPIPreferences")
  #TODO 
  #TODO   - name: use system MPI
  #TODO     shell: julia --color=yes --project=. {0}
  #TODO     run: |
  #TODO       using MPIPreferences
  #TODO       MPIPreferences.use_system_binary()
  #TODO 
  #TODO   - uses: julia-actions/julia-runtest@v1
  #TODO 
  #TODO test-intel-linux:
  #TODO   timeout-minutes: 20
  #TODO   strategy:
  #TODO     matrix:
  #TODO       include:
  #TODO         - container: ghcr.io/juliaparallel/github-actions-buildcache:intel-mpi-jq
  #TODO           name: "Intel MPI 2019.9.304"
  #TODO         - container: ghcr.io/juliaparallel/github-actions-buildcache:intel-oneapi-mpi-jq
  #TODO           name: "Intel oneAPI MPI 2021.11.0"
  #TODO 
  #TODO     fail-fast: false
  #TODO 
  #TODO   runs-on: ubuntu-latest
  #TODO   container: ${{ matrix.container }}
  #TODO   name: "Test ${{ matrix.name }}"
  #TODO 
  #TODO   env:
  #TODO     JULIA_MPI_TEST_BINARY: system
  #TODO     JULIA_MPI_TEST_ABI: MPICH
  #TODO 
  #TODO   steps:
  #TODO   - name: Checkout
  #TODO     uses: actions/checkout@v6
  #TODO 
  #TODO   - uses: julia-actions/setup-julia@v2
  #TODO     with:
  #TODO       version: "1"
  #TODO 
  #TODO   - uses: julia-actions/cache@v3
  #TODO   - name: add MPIPreferences
  #TODO     shell: julia --color=yes --project=. {0}
  #TODO     run: |
  #TODO       using Pkg
  #TODO       Pkg.develop(path="lib/MPIPreferences")
  #TODO 
  #TODO   - name: use system MPI
  #TODO     run: |
  #TODO       julia --color=yes --project=. -e '
  #TODO         using MPIPreferences
  #TODO         MPIPreferences.use_system_binary()'
  #TODO 
  #TODO   - uses: julia-actions/julia-runtest@v1
  #TODO 
  #TODO 
  #TODO test-system-msmpi:
  #TODO   timeout-minutes: 20
  #TODO   strategy:
  #TODO     matrix:
  #TODO       julia_version:
  #TODO         - "1"
  #TODO 
  #TODO     fail-fast: false
  #TODO 
  #TODO   runs-on: windows-latest
  #TODO 
  #TODO   steps:
  #TODO   - name: Checkout
  #TODO     uses: actions/checkout@v6
  #TODO 
  #TODO   - name: Download Microsoft MPI
  #TODO     run: (new-object net.webclient).DownloadFile("https://download.microsoft.com/download/a/5/2/a5207ca5-1203-491a-8fb8-906fd68ae623/msmpisetup.exe", "msmpisetup.exe")
  #TODO     shell: powershell
  #TODO 
  #TODO   - name: Install Microsoft MPI
  #TODO     run: msmpisetup.exe -unattend -minimal
  #TODO     shell: cmd
  #TODO 
  #TODO   - uses: julia-actions/setup-julia@v2
  #TODO     with:
  #TODO       version: ${{ matrix.julia_version }}
  #TODO 
  #TODO   - uses: julia-actions/cache@v3
  #TODO   - name: add MPIPreferences
  #TODO     shell: julia --color=yes --project=. {0}
  #TODO     run: |
  #TODO       using Pkg
  #TODO       Pkg.develop(path="lib/MPIPreferences")
  #TODO 
  #TODO   - name: add MPIPreferences, use system
  #TODO     shell: julia --color=yes --project=test {0}
  #TODO     run: |
  #TODO       using Pkg
  #TODO       Pkg.develop(path="lib/MPIPreferences")
  #TODO       using MPIPreferences
  #TODO       MPIPreferences.use_system_binary(;
  #TODO         export_prefs=true,
  #TODO         mpiexec="C:\\Program Files\\Microsoft MPI\\Bin\\mpiexec"
  #TODO       )
  #TODO       rm("test/Manifest.toml")
  #TODO 
  #TODO   - uses: julia-actions/julia-runtest@v1
  #TODO 
  #TODO 
  #TODO test-mpitrampoline-jll:
  #TODO   timeout-minutes: 20
  #TODO   strategy:
  #TODO     matrix:
  #TODO       os:
  #TODO         - macos-15-intel
  #TODO         - ubuntu-latest
  #TODO       mpi: [mpitrampoline]
  #TODO       julia_version:
  #TODO         - "min"
  #TODO         - "1"
  #TODO         - "nightly"
  #TODO       julia_arch:
  #TODO         - x64
  #TODO         - x86
  #TODO       exclude:
  #TODO         - os: macos-15-intel
  #TODO           julia_arch: x86
  #TODO 
  #TODO     fail-fast: false
  #TODO 
  #TODO   runs-on: ${{ matrix.os }}
  #TODO   env:
  #TODO     JULIA_MPI_TEST_BINARY: MPItrampoline_jll
  #TODO     JULIA_MPI_TEST_ABI: MPItrampoline
  #TODO 
  #TODO   steps:
  #TODO   - name: Checkout
  #TODO     uses: actions/checkout@v6
  #TODO 
  #TODO   - uses: julia-actions/setup-julia@v2
  #TODO     with:
  #TODO       version: ${{ matrix.julia_version }}
  #TODO 
  #TODO   - uses: julia-actions/cache@v3
  #TODO 
  #TODO   - name: add MPIPreferences
  #TODO     shell: julia --color=yes --project=. {0}
  #TODO     run: |
  #TODO       using Pkg
  #TODO       Pkg.develop(path="lib/MPIPreferences")
  #TODO 
  #TODO   - name: use MPItrampoline_jll
  #TODO     shell: julia --color=yes --project=test {0}
  #TODO     run: |
  #TODO       using Pkg
  #TODO       Pkg.develop(path="lib/MPIPreferences")
  #TODO       using MPIPreferences
  #TODO       MPIPreferences.use_jll_binary("MPItrampoline_jll", export_prefs=true)
  #TODO       rm("test/Manifest.toml")
  #TODO 
  #TODO   - uses: julia-actions/julia-runtest@v1
  #TODO 
  #TODO 
  #TODO test-mpitrampoline-system-apt:
  #TODO   timeout-minutes: 20
  #TODO   strategy:
  #TODO     matrix:
  #TODO       mpi:
  #TODO         # MPICH in Ubuntu is currently broken: https://github.com/pmodels/mpich/issues/7064
  #TODO         # - libmpich-dev
  #TODO         - libopenmpi-dev
  #TODO       julia_version:
  #TODO         - "1"
  #TODO         # We don't need to test all combinations
  #TODO         # - "1.7"
  #TODO         # - "nightly"
  #TODO       MPIWrapper:
  #TODO         - "2.11.0"
  #TODO 
  #TODO     fail-fast: false
  #TODO 
  #TODO   runs-on: ubuntu-24.04
  #TODO 
  #TODO   env:
  #TODO     JULIA_MPI_TEST_BINARY: MPItrampoline_jll
  #TODO     JULIA_MPI_TEST_ABI: MPItrampoline
  #TODO     MPITRAMPOLINE_LIB: /usr/local/lib/libmpiwrapper.so
  #TODO     MPITRAMPOLINE_MPIEXEC: /usr/bin/mpiexec
  #TODO     OMPI_MCA_btl_base_warn_component_unused: 0
  #TODO     OMPI_MCA_rmaps_base_oversubscribe: true
  #TODO 
  #TODO   steps:
  #TODO   - name: Checkout
  #TODO     uses: actions/checkout@v6
  #TODO 
  #TODO   - name: Install MPI via apt
  #TODO     run: |
  #TODO       sudo apt-get update
  #TODO       sudo apt-get install $MPI
  #TODO     env:
  #TODO       MPI: ${{ matrix.mpi }}
  #TODO 
  #TODO   - name: Build MPIwrapper
  #TODO     run: |
  #TODO       wget https://github.com/eschnett/MPIwrapper/archive/refs/tags/v${MPIWrapper}.tar.gz
  #TODO       tar xzf v${MPIWrapper}.tar.gz
  #TODO       cd MPIwrapper-*
  #TODO       cmake -DMPIEXEC_EXECUTABLE=mpiexec -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr/local .
  #TODO       cmake --build .
  #TODO       sudo cmake --install .
  #TODO     env:
  #TODO       MPIWrapper: ${{matrix.MPIWrapper}}
  #TODO 
  #TODO   - uses: julia-actions/setup-julia@v2
  #TODO     with:
  #TODO       version: ${{ matrix.julia_version }}
  #TODO 
  #TODO   - uses: julia-actions/cache@v3
  #TODO 
  #TODO   - name: add MPIPreferences
  #TODO     shell: julia --color=yes --project=. {0}
  #TODO     run: |
  #TODO       using Pkg
  #TODO       Pkg.develop(path="lib/MPIPreferences")
  #TODO 
  #TODO   - name: use MPItrampoline_jll
  #TODO     shell: julia --color=yes --project=test {0}
  #TODO     run: |
  #TODO       using Pkg
  #TODO       Pkg.develop(path="lib/MPIPreferences")
  #TODO       using MPIPreferences
  #TODO       MPIPreferences.use_jll_binary("MPItrampoline_jll", export_prefs=true)
  #TODO       rm("test/Manifest.toml")
  #TODO 
  #TODO   - uses: julia-actions/julia-runtest@v1
  #TODO 
  #TODO 
  #TODO test-mpitrampoline-oneapi-linux:
  #TODO   timeout-minutes: 20
  #TODO   strategy:
  #TODO     matrix:
  #TODO       julia_version:
  #TODO         - "1"
  #TODO       MPIWrapper:
  #TODO         - "2.11.0"
  #TODO 
  #TODO     fail-fast: false
  #TODO 
  #TODO   runs-on: ubuntu-latest
  #TODO   container: ghcr.io/juliaparallel/github-actions-buildcache:intel-oneapi-mpi-jq
  #TODO 
  #TODO   env:
  #TODO     JULIA_MPI_TEST_BINARY: MPItrampoline_jll
  #TODO     JULIA_MPI_TEST_ABI: MPItrampoline
  #TODO     MPITRAMPOLINE_LIB: /usr/local/lib/libmpiwrapper.so
  #TODO 
  #TODO   steps:
  #TODO   - name: Checkout
  #TODO     uses: actions/checkout@v6
  #TODO 
  #TODO   - name: Set MPITRAMPOLINE_MPIEXEC
  #TODO     run: echo "MPITRAMPOLINE_MPIEXEC=$(which mpiexec)" >> "${GITHUB_ENV}"
  #TODO 
  #TODO   - name: Build MPIwrapper
  #TODO     run: |
  #TODO       apt-get update
  #TODO       apt-get install -y wget cmake gcc g++ gfortran python3
  #TODO       wget https://github.com/eschnett/MPIwrapper/archive/refs/tags/v${MPIWrapper}.tar.gz
  #TODO       tar xzf v${MPIWrapper}.tar.gz
  #TODO       cd MPIwrapper-*
  #TODO       cmake \
  #TODO           -DMPIEXEC_EXECUTABLE=mpiexec \
  #TODO           -DCMAKE_BUILD_TYPE=Debug \
  #TODO           -DCMAKE_INSTALL_PREFIX=/usr/local \
  #TODO           .
  #TODO       cmake --build .
  #TODO       cmake --install .
  #TODO     env:
  #TODO       MPIWrapper: ${{matrix.MPIWrapper}}
  #TODO 
  #TODO   - uses: julia-actions/setup-julia@v2
  #TODO     with:
  #TODO       version: ${{ matrix.julia_version }}
  #TODO 
  #TODO   - uses: julia-actions/cache@v3
  #TODO 
  #TODO   - name: add MPIPreferences
  #TODO     shell: julia --color=yes --project=. {0}
  #TODO     run: |
  #TODO       using Pkg
  #TODO       Pkg.develop(path="lib/MPIPreferences")
  #TODO 
  #TODO   - name: use MPItrampoline_jll
  #TODO     shell: julia --color=yes --project=test {0}
  #TODO     run: |
  #TODO       using Pkg
  #TODO       Pkg.develop(path="lib/MPIPreferences")
  #TODO       using MPIPreferences
  #TODO       MPIPreferences.use_jll_binary("MPItrampoline_jll", export_prefs=true)
  #TODO       rm("test/Manifest.toml")
  #TODO 
  #TODO   - uses: julia-actions/julia-runtest@v1
  #TODO 
  #TODO 
  #TODO test-spack-mvapich:
  #TODO   timeout-minutes: 20
  #TODO   strategy:
  #TODO     matrix:
  #TODO       include:
  #TODO         - container: ghcr.io/juliaparallel/github-actions-buildcache:mvapich2-jq
  #TODO           name: "MVAPICH 2.3.7"
  #TODO         - container: ghcr.io/juliaparallel/github-actions-buildcache:mvapich3-jq
  #TODO           name: "MVAPICH 3.0"
  #TODO 
  #TODO     fail-fast: false
  #TODO 
  #TODO   runs-on: ubuntu-22.04
  #TODO   container: ${{ matrix.container }}
  #TODO   name: "Test ${{ matrix.name }}"
  #TODO 
  #TODO   env:
  #TODO     JULIA_MPI_TEST_BINARY: system
  #TODO     JULIA_MPI_TEST_EXCLUDE: test_spawn.jl
  #TODO     MV2_SMP_USE_CMA: 0
  #TODO     # Work around issue with affinity not set.  Ref:
  #TODO     # https://github.com/JuliaParallel/MPI.jl/pull/810#issuecomment-1920255386
  #TODO     # MVAPICH 2 and 3 use different environment variables; set both.
  #TODO     MV2_ENABLE_AFFINITY: 0
  #TODO     MVP_ENABLE_AFFINITY: 0
  #TODO 
  #TODO   steps:
  #TODO   - name: Checkout
  #TODO     uses: actions/checkout@v6
  #TODO 
  #TODO   - uses: julia-actions/setup-julia@v2
  #TODO     with:
  #TODO       version: "1"
  #TODO 
  #TODO   - uses: julia-actions/cache@v3
  #TODO   - name: add MPIPreferences
  #TODO     shell: julia --color=yes --project=. {0}
  #TODO     run: |
  #TODO       using Pkg
  #TODO       Pkg.develop(path="lib/MPIPreferences")
  #TODO       Pkg.precompile()
  #TODO 
  #TODO   - name: use system MPI
  #TODO     shell: julia --color=yes --project=. {0}
  #TODO     run: |
  #TODO       using MPIPreferences
  #TODO       MPIPreferences.use_system_binary()
  #TODO 
  #TODO   - uses: julia-actions/julia-runtest@v1
